### ISSUE TITLE
Proxy strains does not work on URL path

### ISSUE THREAD

**Issue by hirenoble** [adobe/helix-publish#64]
**Description**
Proxy strain works for host but not on the full URL path.

**To Reproduce**
  - name: support-production
    origin: https://adobedocs.github.io/developer-support/
    url: https://developer.adobe.com/support

**Expected behavior**
fetching origin from https://adobedocs.github.io/developer-support/

**Screenshots**
fetches https://adobedocs.github.io/support
![image](https://user-images.githubusercontent.com/3747836/57040796-bf3fed80-6c1d-11e9-800b-0e197220fb2c.png)

**Version:**
1.0.0

**Additional context**
Current proxy strain creates rule for host but doesn't take path into consideration.

  set req.http.host = "adobedocs.github.io";

it should be:
set req.http.host = "adobedocs.github.io";
set req.url = "/developer-support/";

**Comment by trieloff** [comment]
Hi @hirenoble - that's definitely a bug. Thanks for reporting.

**Comment by trieloff** [comment]
I had another look at it, and it's a missing feature, not a bug. Something we want to have nonetheless, but it will take a bit of work.

**Comment by trieloff** [comment]
As a quick workaround, you might want to align the two paths, so either have `/support` in both sites or `/developer-support` in both sites. I may need until next week to get this fixed.

**Comment by hirenoble** [comment]
@trieloff, Thank you for looking into this. I tried your suggested approach to change the github page URL to /support. Now I'm seeing another issue. https://developer.adobe.com/support is simply redirecting to https://adobedocs.github.io/support whereas what I want is to browser URL to remain https://developer.adobe.com/support and it should serve the content from github page.

Here is an example of the expected behavior: https://anything.helix-demo.xyz/support

VCL I used:
sub vcl_miss
{
  if(req.url == "/support" || req.url == "/support/"){
    set req.backend = F_Github;
    set bereq.http.host = "adobedocs.github.io";
    set bereq.url = "/support/";
  }
}

so in helix proxy->Fastly rules we may want to set bereq.http.host and bereq.url

**Comment by trieloff** [comment]
Yep, in `adobe/helix-shared#104` I have added the ability to set the `override_host` property, which is exactly what you need.

**Comment by hirenoble** [comment]
@trieloff It's because the GitHub pages behavior, `https://adobedocs.github.io/support` it will give you a 301 redirect if you hit `https://adobedocs.github.io/support/` it gives 200 OK.

so currently https://developer.adobe.com/support/ gives us the expected result whereas https://developer.adobe.com/support will get redirected. 

I think with your fix to have proxy on full path url this should get fixed as we will be mapping developer.adobe.com/support to adobedocs.github.io/support/

**Comment by trieloff** [comment]
You might also want to try to add a redirect rule:
```yaml
redirects:
  - from: ^/support$
    to: /support/
```
the redirect rule should be executed before the request hits the GitHub backend, so you'll never see the faulty redirect from GitHub.

**Comment by trieloff** [comment]
Fixed, but requires `hlx-cli>=2.0.0`

**Comment by filmaj** [comment]
Still seeing the same issue w/ helix-cli 2.1.6.

Relevant helix config part:

```
  - name: support-staging
    origin: https://adobedocs.github.io/developer-support/
    url: https://adobedevsite.helix-demo.xyz/support
```

Run `hlx up --host adobedevsite.helix-demo.xyz --local-repo=.`, then load http://localhost:3000/support

Get a 404 page, and `hlx up` output says:

```
[hlx] info: Proxy GET request to https://adobedocs.github.io:443/support
```

The expectation is that `hlx up` output would provide the correct path to the github.io URL.

**Comment by trieloff** [comment]
Closing this one, as adobe/helix-simulator#213 is the correct issue for the localhost scenario.
